apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce # ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: ""
  claimRef:
    namespace: grafana
    name: grafana
  hostPath:
    path: "/opt/data/grafana"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: ""
  claimRef:
    namespace: loki
    name: loki
  hostPath:
    path: "/opt/data/loki"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: prometheus
    name: prometheus-alertmanager
  hostPath:
    path: /opt/data/prometheus-am
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-local
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: prometheus
    name: prometheus-server
  hostPath:
    path: /opt/data/prometheus-server
