---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kelos-console-auth
  namespace: kelos-system
spec:
  encryptedData:
    token: AgBM5HnY8Ih+nopLVlOHTk+FErK16jQBiMup5Nr4WRlhTlrC2/oGp9sweXvfbeM2zc4b5D/g+7K2QFlKHLFqZO3d2bifHFQbhNwiX4dS5/mc3U43jM5Fe7JvVDsJy0V52UY3hz/u1AnVja+XTtUg90IloHGCSme31XMqw5iAzkHEZTUyJO9JihhfBWZxphAJH+qybMzvw03I+D64DCBbUvplTo+B9aczG63V08ZDyLTxKWmh7PCsgsFXlQl4jo72ujzehlNry51PdcSYx7Lg6Q6DeGG9zz4aGLKb/uJ1pqbJbPIasChZwMR1vZahD3x3+BBMNBIKisC2wVJEnat80sFoStTZPMQBxDBa3dbu8ElZ0j4Hrxc0/qrm1TYm/fc+FONpKfzTbeGjnEhkgibZQWu15+MlXmdquSjGYDk6j3qU0TBg04IhWfLxlGkwODT3LNBhZH6EocwE0WHxqKxqlod9OTGFDR/d4VPewuvzHzSnLfzXV/Q4mFDzP8YDKh+VCblxEL0M0uz+Cenu9pH+1HXQbtpESKzRX6bKVXwbrXAjhbgXSfb1TJj/KeEgmR9Fw5bMudvyeeGchqmSxiVjSkuNBvJBYrynWxHffnMwJOVt5M52ZBDjcwhchpNh/aLOWTojyj8NwbD1gDEF4WuJ1PJcVnRcw92qvmIyGKV6RRE1jfyypRzM7DUwZornNt8IrnlRVeier4Zzfs2E9AUTQZxzgpC7/ElDOJlIqWQqeRu6uB61zFPhEBhlNEx9S5UiE4A+nFxKxu5oqn1tNHCj9+0b
  template:
    metadata:
      name: kelos-console-auth
      namespace: kelos-system
