apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firecrawl-postgres-pvc
  namespace: pantrywise
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
