apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pantrywise
  labels:
    app: pantrywise-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pantrywise-redis
  template:
    metadata:
      labels:
        app: pantrywise-redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: docker.io/library/redis:7-alpine
          command: ["redis-server", "--appendonly", "yes"]
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command: [redis-cli, ping]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [redis-cli, ping]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 256Mi
