---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radar-argocd-token
  namespace: radar
spec:
  encryptedData:
    token: AgAx6Dipn3vDqwKBFX2eIBJuZxZ/PCaHjMvWx2aBz+gr86b3zHCF750ih5Kq9ulj+RJezeGfCb/tMpq4+pjv6DGatMWkUdOmlIZn3xyBJ7RL0QSNX7IVlZzzd2dPRoSXrU+fJ+cv1EB9thzWBD5eYlaOhJlokBZiOTg3XbGLw5MskpRNMeOXF1algogfyhe/Lb+jrf8XGKzwlr4nJU+ns1uoQrYAMAjJDP11DSWc0LEYTHsd4Z2gsvVa24w830alw6vqIS5TLONZRLC2HtfWLMOH6zgfIYYEFsnBeI9iisdgoQ8ADFOC8fW7lB7/0I1rHFoqh27kB0i0qO574BDUHQTExtEiGQskBNjartPjPsnIMe+5SOkIsEUoeQXWJG0Jw2RqYwIOoHsAZQylIWb52TMQM8rIZkiqFatsmPmeYyWm0BXrvcRWpEy/8UB6MgQNA4+DpSfovmYURL5micn9CSesMKuYHjG75m+4Btf7TFWE5D2kTRHD0ZB4LqiORIp57RI+zk07OYHHfGvwpp81aaC48IWcoBBmvULu/k9pLSO+FRZen0dDRmMHgKCEvSbQWxT9BdDnif+zuVFkPMHT1OqgL7AM6w+45aboldVjqnbgFnGLLEbad5w32rtULhZR/qQX4RKs/zHxYbiMYejBP/CB3eilNEd8+BEiDGCWZRTPj1+6zMKOJbZPowEZzIK7OOBsFpqL3uXA7AWLUaP6jATI3ahZ9y6l+nCO0kiAiGmCTbjR+V7CS22B+l+3PGCupcQi0YbMz3Mfy09jGIgYCx25zz9QiwxaIFzbRDoHozkwDWi+9C+DAlwjOLrB1x5Wrc3P2owDCBakN3vhnpwJalqTLnemNJRDUfAXLZ/zLQDaikji/+Xmd8hIeOxUz/ztfZnJH+M10xitdtz0Mkn4Q/lforbeY/2LDSddTiJ3wnVPWwSrU6Qz4eDLkK6ggGSoN2ggbb+Dl4lm
  template:
    metadata:
      name: radar-argocd-token
      namespace: radar
