apiVersion: v1
kind: Service
metadata:
  name: litellm-postgres
  namespace: litellm
spec:
  type: ClusterIP
  selector:
    app: litellm-postgres
  ports:
    - port: 5432
      targetPort: pg
      protocol: TCP
