apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: k3s-lab
  source:
    repoURL: https://github.com/djdanielsson/k3s_lab
    targetRevision: gitops-fresh
    path: apps/glance
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
