apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-bitwarden
  namespace: argocd
spec:
  project: k3s-lab
  source:
    repoURL: https://github.com/djdanielsson/k3s_lab
    targetRevision: main
    path: apps/eso-bitwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
