apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: k3s-lab
  source:
    repoURL: https://github.com/djdanielsson/k3s_lab
    targetRevision: gitops-fresh
    path: apps/registry
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false