apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - application-registry.yaml
  - application-pantrywise.yaml
  - application-rustfs.yaml
  - application-radar.yaml
  - application-cert-manager.yaml
  - application-sealed-secrets.yaml
  - application-forgejo.yaml
  - application-netdata.yaml
  - application-netalertx.yaml
  - application-glance.yaml
  - application-cert-manager-issuers.yaml
  - application-ingress.yaml
  - application-dnsmasq.yaml
