---
name: kubeshark
apiVersion: v2
version: 1.0.0
dependencies:
  - name: kubeshark
    version: 52.3.62
    repository: https://helm.kubeshark.co
    spec:
      source:
        helm:
          values: |
            tap:
              ingress:
                enabled: true
                host: kubeshark.lab.danielsson.us.com
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              annotations:
                nginx.org/websocket-services: "kubeshark-front"
              name: kubeshark-ingress
              namespace: default
            spec:
              rules:
                - host: kubeshark.lab.danielsson.us.com
                  http:
                    paths:
                      - backend:
                          service:
                            name: kubeshark-front
                            port:
                              number: 80
                        path: /
                        pathType: Prefix