frontend:
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: signoz.lab.danielsson.us.com
        paths:
          - path: /
            pathType: Prefix
            port: 3301

ingress-nginx:
  enabled: true

otelCollector:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: signoz.lab.danielsson.us.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 4317
