---
- name: Deploy ArgoCD on k3s
  hosts: all
  gather_facts: true
  become: true
  vars:
    awx_on_k3s_local_hosts: false
    awx_on_k3s_deploy_k3s: true
    awx_on_k3s_secure_logging: true
    ansible_python_interpreter: ~/ansible/bin/python3
    awx_on_k3s_disable_services:
      - firewalld
      - nm-cloud-setup.service
      - nm-cloud-setup.timer
    awx_on_k3s_hosts_lines:
      - "{{ ansible_facts['default_ipv4']['address'] }} awx.lab.danielsson.us.com"
      - "{{ ansible_facts['default_ipv4']['address'] }} galaxy.lab.danielsson.us.com"
      - "{{ ansible_facts['default_ipv4']['address'] }} eda.lab.danielsson.us.com"
      - "{{ ansible_facts['default_ipv4']['address'] }} argocd.lab.danielsson.us.com"
    awx_on_k3s_awx_dirs:
      - path: /data/postgres-15/data
        owner: 26:0
        mode: "0775"
      - path: /data/projects
        owner: 1000:0
        mode: "0755"
      - path: /data/galaxy/postgres-13
        owner: root
        mode: "0755"
      - path: /data/galaxy/redis
        owner: root
        mode: "0755"
      - path: /data/galaxy/file
        owner: 1000:0
        mode: "0755"
      - path: /data/eda/postgres-13/data
        owner: 26:0
        mode: "0775"
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - name: Disable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      failed_when: false
      # notify:
      #   - Reboot
      loop: "{{ awx_on_k3s_disable_services }}"

    # Cannot reboot when running against localhost but in the future could be run from other system
    # - name: Flush handlers
    #   ansible.builtin.meta: flush_handlers

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - git
          - curl
        state: present

    - name: Ensure python packages are installed
      ansible.builtin.pip:
        name:
          - cryptography
          - kubernetes
          - kubernetes-validate
        state: present

    - name: For /etc/hosts option
      when: awx_on_k3s_local_hosts
      block:
        - name: Add lines to /etc/hosts
          ansible.builtin.lineinfile:
            path: /etc/hosts
            line: "{{ item }}"
          loop: "{{ awx_on_k3s_hosts_lines }}"
          notify:
            - Daemon-reload
            - Restart dnsmasq

        - name: Install dnsmasq
          ansible.builtin.package:
            name: dnsmasq
            state: present

        - name: Start dnsmasq with default configuration
          ansible.builtin.service:
            name: dnsmasq
            state: started
            enabled: true
          notify:
            - Daemon-reload

        - name: Ensure directory paths exist
          ansible.builtin.file:
            path: /etc/rancher/k3s
            state: directory
            mode: "0755"

        - name: Create new resolv.conf to use K3s
          ansible.builtin.copy:
            dest: /etc/rancher/k3s/resolv.conf
            content: "nameserver {{ ansible_facts['default_ipv4']['address'] }}"
            mode: "0644"
          notify:
            - Daemon-reload

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers

    - name: Install k3s
      ansible.builtin.shell: set -o pipefail && curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 {% if awx_on_k3s_local_hosts is defined %}--resolv-conf /etc/rancher/k3s/resolv.conf{% endif %} # noqa yaml[line-length]
      changed_when: true
      when: awx_on_k3s_deploy_k3s

    - name: Deploy ArgoCD
      block:
        - name: Check if tls keys already exist
          ansible.builtin.stat:
            path: "../upstream/argocd/tls.key"
          register: r_awx_tls_key

        - name: Generate tls when they do not exist
          when: not r_awx_tls_key['stat']['exists']
          block:
            - name: Create private key (RSA, 4096 bits)
              community.crypto.openssl_privatekey:
                path: "../upstream/argocd/tls.key"
                mode: "0644"

            - name: Create certificate signing request (CSR) for self-signed certificate
              community.crypto.openssl_csr_pipe:
                privatekey_path: "../upstream/argocd/tls.key"
                common_name: "argocd.lab.danielsson.us.com"
                subject_alt_name:
                  - "DNS:argocd.lab.danielsson.us.com"
              register: csr

            - name: Create self-signed certificate from CSR
              community.crypto.x509_certificate:
                path: "../upstream/argocd/tls.crt"
                csr_content: "{{ csr.csr }}"
                privatekey_path: "../upstream/argocd/tls.key"
                provider: selfsigned
                mode: "0644"

        - name: Deploy ArgoCD
          kubernetes.core.k8s:
            state: present
            definition: "{{ lookup('kubernetes.core.kustomize', dir='../upstream/argocd/') }}"

        - name: Ensure directories exist and have correct permissions
          ansible.builtin.file:
            path: "{{ item['path'] }}"
            state: directory
            owner: "{{ item['owner'] }}"
            mode: "{{ item['mode'] }}"
          loop: "{{ awx_on_k3s_awx_dirs }}"

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

    - name: Daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted

...
