---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-reader
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances", "virtualmachines"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-reader
subjects:
- kind: ServiceAccount
  name: virtualmachine-reader
  namespace: kubevirt
roleRef:
  kind: ClusterRole
  name: virtualmachine-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualmachine-reader
  namespace: kubevirt
---
apiVersion: v1
kind: Secret
metadata:
  name: virtualmachine-reader-token
  namespace: kubevirt
  annotations:
    kubernetes.io/service-account.name: virtualmachine-reader
type: kubernetes.io/service-account-token