---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-deployer
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances", "virtualmachines"]
  verbs: ["*"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["list"]
- apiGroups: ["upload.cdi.kubevirt.io"]
  resources: ["uploadtokenrequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-deployer
subjects:
- kind: ServiceAccount
  name: virtualmachine-deployer
  namespace: kubevirt
roleRef:
  kind: ClusterRole
  name: virtualmachine-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualmachine-deployer
  namespace: kubevirt
---
apiVersion: v1
kind: Secret
metadata:
  name: virtualmachine-deployer-token
  namespace: kubevirt
  annotations:
    kubernetes.io/service-account.name: virtualmachine-deployer
type: kubernetes.io/service-account-token