---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-op
  namespace: argocd
spec:
  destination:
    namespace: awx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: upstream/awx/operator
    repoURL: https://github.com/djdanielsson/k3s_lab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        external.secrets.io/enabled: "true"
