---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  destination:
    namespace: netdata
    server: https://kubernetes.default.svc
  project: default
  source:
    path: upstream/netdata/
    repoURL: https://github.com/djdanielsson/k3s_lab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        external.secrets.io/enabled: "true"
