---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netdata
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: netdata.lab.danielsson.us.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              # serviceName: netdata
              # servicePort: http
              service:
                name: netdata
                port:
                  name: http