apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ts
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: tailscale-ingress
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kube-prometheus-stack-prometheus
      port:
        number: 9090
