apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: pantrywise }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: forgejo }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: radar }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: glance }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: netdata }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata: { name: k3s, namespace: netalertx }
spec: { type: ingress, replicas: 1, tags: ["tag:k3s"] }
