apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: rustfs
  labels:
    app: rustfs
  annotations:
    tailscale.com/manage: "true"
    tailscale.com/hostname: rustfs
spec:
  type: ClusterIP
  selector:
    app: rustfs
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
