frontend:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: signoz.lab.danielsson.us.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 80
