---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBvfar6Ghkr2GXO/UQ6UNoVtl3v3nurxmDt2jGvCyjtW9KJHYou7Kh+XuXpiyapkm7yqmbdpBP0nQ65F7Sog1mTRNAI4ZhrFaxTQhjR0w24UAry4TVePXrWuOkNquckB7GZNb5uyKM7w1cVp4VEIxXBuW6r51p81M/X9wueV/uSdIo5BAE88bVhYTg2J3SysOr+SC9j6hK3SFgV1nlhIRLGiQM38n28L7qApFYJnwFL0ffnj+upITI31KzETZvK1MUtd+xFCBwZ9+ffZ+zveSa/EJGfI2N5Fmy7ohAeQmj+Qcc+rXomh6vJZvxLhvxA8+DtVAcfcrmDw0ICo9s85LB4ubBRHelsJG1IUFYcoGsuqveJTxF8/pDPaEdLvibLtBSMNm72l+2D+36OqQ0T3R+1A7NSc0A7ysAfXf8gyixe9tSVaDI9CBP1LYnrtvbg97bMUfgT4Ay/LMMbdZdREWY4OGRG/eqIjEt4BvksxnGqZggneyQEd1nDZX/zARIpcY1AKw8fQ2nnv1OGbCjwi/FMSXw8adnu6fWixzWHytwON3GNnD/3QJd0M73WZhbt2th+KA7KFzjL0bVYQ4ZvD9XSPIkjKj8/Nsd2AiIr2PHTLUrlQSzke+XcMdHTBsPrg7IRnsnEtrbOF6xecmYC+CdG2ULbWOkSPscXuHC5+xCas5snvf5zddLsjBbyHgLrDe4n5+RjsBoNfpaMjiUnIv/VnBBpeXykYmKsYwqv
    client_secret: AgAsJAD4mbQAnHFTPz6rvBxHHVs5YwZ35q1YvY9GedVfxw7KxxZ62os/WSEbhMiLB3q7pKdezE9w6uZWmf+AeWZrOZuUZ4pgNlKc09H7fFcGV9QEysyhjldINBQqGl0DI8WMW6L0pafbut4h4sLwNq+wCjSwt6vY63328v/W7wSygkWK2RFTAGh9NME0dk3kh+VZ1GYsYaQy2Q4uPVYuXaEZBRWTZ9yMkOdvXxiSj7SJAbqEEYqjaubtLXlrKT08mWsnu0mQYSuoiQcS5FYZt6T7JBMQ5Pc+yaP8rakGV8FkEln/gjbzqMwD2GAoB7tq7uUcgRjydpB9Phyi49fTUcoatUbY63m21LPxpC/vrjz7XjZ9lIgxpwhpw9ILU3sbYCrsdzN2B/DHcd8GXykJvPj0+2JtBPeDBH8pnrWmcwLkphDEGoV4CTLgZw7KCZfSpLzaQ0eB1knnJq7Tkq6LX6xfWY+gaajPlzjmmoiC13RntedM7acpaUYdgtozEb8AfdO5RF43R564UAeUqRjb/PjL90vKUpbUmc1nRZhowCfwPEKXfHgiNomSnT8d8RHsezcTq9ZnyCTOUTWrQCuJTSM8CvnzZicaT5xrc8VBeSPwC2mDkdLWgnepKEBXgU8ERx/wfbtClYJfX5Xm6BQs8n2qKcfWUNHK8CSpU7dHiwUMgs2DEccxsajeWf5C+FW0/Z4JhNN/PZ7iRN5FkgQwviTz/zXy0/JQTYGFPv8kp4Tnmg==
  template:
    metadata:
      name: tailscale-oauth
      namespace: tailscale
    type: Opaque
